--- #YAML:1.0
name:                CPAN-Unpack
version:             0.23
abstract:            Unpack CPAN distributions
license:             perl
author:              
    - Leon Brocard <acme@astray.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Archive::Extract:              0
    Archive::Tar:                  0
    Archive::Zip:                  0
    Class::Accessor::Chained:      0
    IO::Zlib:                      0
    Parse::CPAN::Packages:         2.21
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
